services:
  fluent:
    image: ghcr.io/ansys/pyfluent:v25.2.0
    environment:
      - ANSYSLMD_LICENSE_FILE=1055@punlnxlicense5.ansys.com
    command: -sifile=/home/container/workdir/serverinfo-9h2so6_o.txt 3ddp -hidden  -meshing
    ports:
      - 61979:61979
    working_dir: /home/container/workdir
    volumes:
      - D:\Repos\pyfluent:/home/container/workdir
  filetransfer:
    image: ghcr.io/ansys/tools-filetransfer:latest
    ports:
      - 61980:61980
    working_dir: /home/container/workdir
    volumes:
      - D:\Repos\pyfluent:/home/container/workdir
